import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { theme } from '@/constants/theme';
import { useAiken } from '@/context/AikenContext';
import { Card, Icon, PrimaryButton, SectionTitle } from '@/components/UI';

export default function ScheduleScreen() {
  const insets = useSafeAreaInsets();
  const { events, focusSessions } = useAiken();
  const [monthOffset, setMonthOffset] = useState(0);
  const month = useMemo(() => { const date = new Date(); date.setMonth(date.getMonth() + monthOffset); return date; }, [monthOffset]);
  const first = new Date(month.getFullYear(), month.getMonth(), 1);
  const daysInMonth = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
  const leading = (first.getDay() + 6) % 7;
  const cells = Array.from({ length: leading + daysInMonth }, (_, index) => index < leading ? null : index - leading + 1);
  const monthEvents = events.filter((event) => { const date = new Date(event.start); return date.getMonth() === month.getMonth() && date.getFullYear() === month.getFullYear(); });
  return <ScrollView style={styles.page} contentContainerStyle={[styles.content, { paddingTop: insets.top + 14, paddingBottom: 120 }]} showsVerticalScrollIndicator={false}>
    <View style={styles.topRow}><View><Text style={styles.eyebrow}>Your rhythm</Text><Text style={styles.title}>Schedule Calendar</Text><Text style={styles.subtitle}>See the month without losing the details.</Text></View><View style={styles.monthToggle}><Pressable onPress={() => setMonthOffset((value) => value - 1)}><Icon name="chevron-left" size={17} color={theme.maroon} /></Pressable><Text style={styles.monthLabel}>{month.toLocaleDateString(undefined, { month: 'short' })}</Text><Pressable onPress={() => setMonthOffset((value) => value + 1)}><Icon name="chevron-right" size={17} color={theme.maroon} /></Pressable></View></View>
    <Card style={styles.calendarCard}><Text style={styles.monthTitle}>{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</Text><View style={styles.weekdays}>{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <Text key={`${day}-${index}`} style={styles.weekday}>{day}</Text>)}</View><View style={styles.days}>{cells.map((day, index) => { const hasEvent = day && monthEvents.some((event) => new Date(event.start).getDate() === day); const isToday = day === new Date().getDate() && month.getMonth() === new Date().getMonth(); return <View key={`${day}-${index}`} style={[styles.cell, isToday && styles.todayCell]}>{day && <Text style={[styles.cellText, isToday && styles.todayText]}>{day}</Text>}{hasEvent && <View style={styles.eventDot} />}</View>; })}</View></Card>
    <SectionTitle eyebrow="At a glance" title="Your week" />
    <View style={styles.statGrid}><Card style={styles.stat}><View style={[styles.statIcon, { backgroundColor: '#FDE8E8' }]}><Icon name="flag" size={17} color={theme.maroon} /></View><Text style={styles.statValue}>{events.filter((event) => event.type === 'deadline').length}</Text><Text style={styles.statLabel}>Deadlines ahead</Text></Card><Card style={styles.stat}><View style={[styles.statIcon, { backgroundColor: '#E7F2EA' }]}><Icon name="check-circle" size={17} color={theme.green} /></View><Text style={styles.statValue}>{focusSessions.length}</Text><Text style={styles.statLabel}>Focus sessions</Text></Card></View>
    <Card style={styles.focusCard}><View style={{ flex: 1 }}><Text style={styles.focusEyebrow}>Make space for what matters</Text><Text style={styles.focusTitle}>A 25-minute focus block is enough to start.</Text><Text style={styles.focusText}>Aiken checks your calendar first so your suggested blocks never overlap.</Text></View><PrimaryButton label="Open Aiken" icon="message-circle" onPress={() => {}} style={styles.smallButton} /></Card>
  </ScrollView>;
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: theme.cream }, content: { paddingHorizontal: 18 }, topRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 22 }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 11, color: theme.maroon, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 }, title: { fontFamily: 'Inter_700Bold', fontSize: 27, color: theme.ink, letterSpacing: -0.6 }, subtitle: { fontFamily: 'Inter_400Regular', color: theme.mutedInk, fontSize: 13, marginTop: 5 }, monthToggle: { marginTop: 4, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: theme.amberSoft, paddingVertical: 8, paddingHorizontal: 10, borderRadius: theme.radius.pill }, monthLabel: { color: theme.maroon, fontFamily: 'Inter_700Bold', fontSize: 12 }, calendarCard: { padding: 17, marginBottom: 24 }, monthTitle: { color: theme.ink, fontFamily: 'Inter_700Bold', fontSize: 18, marginBottom: 18 }, weekdays: { flexDirection: 'row', marginBottom: 9 }, weekday: { width: '14.28%', textAlign: 'center', color: theme.mutedInk, fontFamily: 'Inter_700Bold', fontSize: 11 }, days: { flexDirection: 'row', flexWrap: 'wrap' }, cell: { width: '14.28%', height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 13, position: 'relative' }, todayCell: { backgroundColor: theme.amber }, cellText: { fontFamily: 'Inter_600SemiBold', color: theme.ink, fontSize: 13 }, todayText: { color: theme.ink }, eventDot: { position: 'absolute', bottom: 7, width: 5, height: 5, borderRadius: 3, backgroundColor: theme.maroon }, statGrid: { flexDirection: 'row', gap: 12, marginBottom: 16 }, stat: { flex: 1 }, statIcon: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, statValue: { color: theme.ink, fontFamily: 'Inter_700Bold', fontSize: 25 }, statLabel: { color: theme.mutedInk, fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 3 }, focusCard: { backgroundColor: theme.maroon, flexDirection: 'row', gap: 12, alignItems: 'flex-end' }, focusEyebrow: { color: '#F8C978', fontFamily: 'Inter_700Bold', fontSize: 10, textTransform: 'uppercase', letterSpacing: 0.7 }, focusTitle: { color: theme.cream, fontFamily: 'Inter_700Bold', fontSize: 16, lineHeight: 21, marginTop: 7 }, focusText: { color: '#F5D7BC', fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, marginTop: 6 }, smallButton: { backgroundColor: theme.cream, paddingHorizontal: 12, minHeight: 38 },
});